name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
      environment:
        description: 'Test environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - dev
          - stage
      headless:
        description: 'Run in headless mode'
        required: true
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Chrome
        if: ${{ inputs.browser == 'chrome' || inputs.browser == null }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Firefox
        if: ${{ inputs.browser == 'firefox' }}
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest

      - name: Run Tests
        run: |
          browser="${{ inputs.browser || 'chrome' }}"
          env="${{ inputs.environment || 'qa' }}"
          headless="${{ inputs.headless || 'true' }}"
          mvn clean test -B -Dbrowser=$browser -Denv=$env -Dheadless=$headless

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ inputs.browser || 'chrome' }}-${{ inputs.environment || 'qa' }}
          path: |
            target/surefire-reports/
            test-output/
          retention-days: 30
          compression-level: 9 # Maximum compression
          overwrite: true # Override if exists

      - name: Test Summary
        if: always()
        run: |
          echo "Test Execution Summary:"
          echo "Browser: ${{ inputs.browser || 'chrome' }}"
          echo "Environment: ${{ inputs.environment || 'qa' }}"
          echo "Headless Mode: ${{ inputs.headless || 'true' }}"
          echo "Results available in the Artifacts section"